[project]
name = "dgpsi-picu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7,<3.11"
dependencies = [
    "dgpsi>=2.5.0",
    "pandas>=1.1.5",
    "seaborn>=0.12.2",
]
